on: 
  push:
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps: 
      - name: echo
        run: |
          echo "running"
      - name: echo if release 1
        if: github.ref == 'refs/heads/release/**'
        run: |
          echo "condition is github.ref == 'refs/heads/release/**'"
      - name: echo if release 2
        if: startsWith(github.ref, 'refs/heads/release')
        run: |
          echo "condition is startsWith(github.ref, 'refs/heads/release')"
