on: 
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ENVIRONMENT variable
        run: |
          if true; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          fi
      - name: echo
        run: |
          echo $ENVIRONMENT
      - name: pwd
        run: |
          pwd
      - name: working_dir
        working-directory: ./test
        run: |
          ls
