name: StoryBook Deploy S3[pull_request]

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      S3_URL: s3_demo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_ENDPOINT: ${{ github.event.issue.pull_request.url }}
      GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.issue.number }}
    steps:
        - name: Create URL
          run: |
            curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -i ${API_ENDPOINT} -d "`printf '{\"body\":\"deploy to %s\"}' ${S3_URL}/"pr-"${GITHUB_PULL_REQUEST_NUMBER}`"