name: StoryBook Deploy S3[pull_request]

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S3_URL: s3_demo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_ENDPOINT: ${{ github.event.issue.pull_request.url }}
      GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.issue.number }}
    steps:
        - name: echo1
          run:
            echo GITHUB_TOKEN is ${GITHUB_TOKEN}.
        - name: echo2
          run:
            echo GITHUB_TOKEN is ${API_ENDPOINT}.
        - name: echo3
          uses: actions/github-script@v3
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Thanks for reporting!'
              })